### ISSUE TITLE
How to get details from errors

### ISSUE THREAD

**Issue by luizfbicalho** [AdaskoTheBeAsT/Typewriter#18]
I have this errors in my templates, 

```
15:12:59.865 ERROR: Error rendering template. Cannot get identifier 'ImportReference'. Source path: C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.ASpnetCore.Identity.Controllers\Configuracao\ConstantesPermissao.cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at __Typewriter.Template.ModelProperties(Class clas)
   at __Typewriter.Template.ImportReference(Class clas)
15:12:59.877 ERROR: Error rendering template. Cannot get identifier 'AssociationProperties'. Source path: C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.ASpnetCore.Identity.Controllers\Configuracao\ConstantesPermissao.cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at __Typewriter.Template.ModelProperties(Class clas)
   at __Typewriter.Template.AssociationProperties(Class clas)
```

How can I inspect oe understand whats going on.

**Comment by AdaskoTheBeAsT** [comment]
Hi,

Can you share some fragment in github repo to reproduce?

**Comment by luizfbicalho** [comment]
I think that I wrote really bad my question, this case is solved, but my issue is that I think that would be better to have more information like this for example

```
   at __Typewriter.Template.ModelProperties(Class clas) at line 26
   at __Typewriter.Template.AssociationProperties(Class clas) at line 52
```

**Comment by AdaskoTheBeAsT** [comment]
indeed but still - due to lack of time is not something which I will have time to deal with in near time

**Comment by AdaskoTheBeAsT** [comment]
please check v4 - more verbose error messages should show more info
