### ISSUE TITLE
Destination over 260 characters fails

### ISSUE THREAD

**Issue by JBBianchi** [AdaskoTheBeAsT/Typewriter#37]
Where trying to write a file with a path longer than 260 character, an error is thrown (the path has been changed but the length is the saame):
```
15:53:16.000 ERROR: Error processing queue: Could not find a part of the path 'C:\Dev\SomeInnerPath\Github\Project\src\innerpath\another-subpath\A.Very.Long.Project.Name.Like.Dotnet.People.Like\packages\some-random-scope\some-package-name\src\lib\events\a-very-very-very-very-very-very-very-very-very-very-very-very-very-very-long-file-name.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Typewriter.Generation.Template.SaveFile(File file, String output, Boolean& success)
   at Typewriter.Generation.Template.RenderFile(File file)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass5_1.<OnTemplateChanged>b__1()
   at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()
```

Even though `LongPathsEnabled`is true in the registry:
![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/72747835/7b7ae21b-3939-4ebf-a3a4-71117c407331)

![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/72747835/39f87c9f-ed7e-437b-897c-91b51e1ec95b)

![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/72747835/870007f8-9875-4e57-8b74-5e545aa0475a)

Or via gpedit:
![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/72747835/cbcc029b-2f24-4896-9fea-2c1e354d39a7)

One thing I find odd is that it's not the [System.IO.PathTooLongException](https://learn.microsoft.com/en-us/dotnet/api/system.io.pathtoolongexception?view=netframework-4.7.2) that seems to be thrown but it's definitely related to the 260 char limitation.

I read things about the `Switch.System.IO.UseLegacyPathHandling`, `Switch.System.IO.BlockLongPaths` or ` <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>` in the application manifest but I don't think I have access to those or if they even apply to a VS extension...

Maybe [WriteFile](https://github.com/AdaskoTheBeAsT/Typewriter/blob/36663f37998ad7b59a8c669dcd1e29cc12c86abd/src/Typewriter/Generation/Template.cs#L166) could rely on something else than System.IO, like [ZetaLongPaths ](https://github.com/UweKeim/ZetaLongPaths) or other [workarounds ](https://www.codeproject.com/Articles/22013/NET-2-0-Workaround-for-PathTooLongException)?

// OS: Windows 10/11 x64

**Comment by AdaskoTheBeAsT** [comment]
Indeed let me take a look

**Comment by AdaskoTheBeAsT** [comment]
https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.20.0

**Comment by JBBianchi** [comment]
Now I have this error straight away:
```
10:58:10.124 ERROR: Error processing queue: The filename, directory name, or volume label syntax is incorrect
   at Typewriter.LongPaths.FileWriter.WriteAllText(String path, String contents)
   at Typewriter.Generation.Template.SaveFile(File file, String output, Boolean& success)
   at Typewriter.Generation.Template.RenderFile(File file)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass5_1.<OnTemplateChanged>b__1()
   at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()
```

**Comment by AdaskoTheBeAsT** [comment]
I added small part which creates folder if it is missing - also it seems interop is not needed as System.IO is able to work with long paths when using that magic prefix - can you run test in solution "FileWriterTest" ?
it should pass

**Comment by JBBianchi** [comment]
The test does indeed run successfully.

**Comment by JBBianchi** [comment]
I changed the path in the test to the actual failing one and then the test fails. I think it's because I use `../` in the path.

For instance, by replacing the path in test with
```csharp
var path = @"C:\Dev\..\Dev\SomeInnerPath\Github\Project\src\innerpath\another-subpath\A.Very.Long.Project.Name.Like.Dotnet.People.Like\packages\some-random-scope\some-package-name\src\lib\events\a-very-very-very-very-very-very-very-very-very-very-very-very-very-very-long-file-name.ts";            
``` 

Which is basically the same, then the test fails.

I think it can be fixed by calling `GetFullPath`
```csharp
var path = @"C:\Dev\..\Dev\SomeInnerPath\Github\Project\src\innerpath\another-subpath\A.Very.Long.Project.Name.Like.Dotnet.People.Like\packages\some-random-scope\some-package-name\src\lib\events\a-very-very-very-very-very-very-very-very-very-very-very-very-very-very-long-file-name.ts";
path = System.IO.Path.GetFullPath(path);
```

**Comment by AdaskoTheBeAsT** [comment]
ok thanks
https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.22.0

**Comment by JBBianchi** [comment]
It seems to work flawlessly now. Thanks a lot for your reactivity !
