### ISSUE TITLE
Generated files are in wrong encoding

### ISSUE THREAD

**Issue by qbunia** [AdaskoTheBeAsT/Typewriter#40]
When classes are generated they have windows-1250 encoding instead of original file encoding UTF8. How I can fix this issue?

**Comment by qbunia** [comment]
Newest version broke the extension. Im getting error:
`
23:50:07.885 ERROR: Error processing queue: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Typewriter.Generation.Template.WriteFile(String outputPath, String outputContent)
   at Typewriter.Generation.Template.SaveFile(File file, String output, Boolean& success)
   at Typewriter.Generation.Template.RenderFile(File file)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass5_1.<OnTemplateChanged>b__1()
   at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()
`

**Comment by AdaskoTheBeAsT** [comment]
to investigate I need path in which template exists

**Comment by qbunia** [comment]
Its `C:\Users\Qbusoft\Desktop\DoctorsOfficeGit\AngularTest\src\models`

**Comment by qbunia** [comment]
@AdaskoTheBeAsT did you manage to fix the issue?

**Comment by AdaskoTheBeAsT** [comment]
please download latest version

**Comment by qbunia** [comment]
On latest version it doesnt work. I tested it.

**Comment by AdaskoTheBeAsT** [comment]
this is version which I have
![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/1914201/256f7e92-cc54-427a-bf94-3e6c792bf3fc)

when I generate some file out of tst file without BOM and when I check its encoding in notepad++
it clearly says it is UTF-8

![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/1914201/9a8a39c8-aa79-43e2-a70f-f545d8ef7f1c)

same when I use default

![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/1914201/62349952-77cd-4522-b429-5438369cf915)

**Comment by qbunia** [comment]
The problem is that with newest version I cannot generate anything. I mentioned the bug below.

**Comment by AdaskoTheBeAsT** [comment]
can you enable long paths on your machine?

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001

**Comment by qbunia** [comment]
Unfortunately its not possible.

**Comment by AdaskoTheBeAsT** [comment]
please check this one https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.25.0

**Comment by qbunia** [comment]
Getting same error:
`07:30:07.263 ERROR: Error processing queue: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Typewriter.Generation.Template.WriteFile(String outputPath, String outputContent)
   at Typewriter.Generation.Template.SaveFile(File file, String output, Boolean& success)
   at Typewriter.Generation.Template.RenderFile(File file)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass5_1.<OnTemplateChanged>b__1()
   at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()
`

**Comment by AdaskoTheBeAsT** [comment]
in settings -  do you use option .OutputDirectory() ? if yes is the path either written as 
```csharp
settings..OutputDirectory(@"C:\Users\Qbusoft\Desktop\DoctorsOfficeGit\AngularTest\src\models")
```

or

```csharp
settings..OutputDirectory("C:\\Users\\Qbusoft\\Desktop\\DoctorsOfficeGit\\AngularTest\\src\\models")
```

**Comment by qbunia** [comment]
I dont use OutputDirectory at all in settings. My settings:

 Template(Settings settings)
 {
     settings.IncludeProject("Models");
     settings.OutputExtension = ".d.ts";
     settings.DisableStrictNullGeneration();
     settings.SkipAddingGeneratedFilesToProject = true;
 }

**Comment by qbunia** [comment]
@AdaskoTheBeAsT Did you get my last message?

**Comment by AdaskoTheBeAsT** [comment]
as I checked your file is working on my machine - so it is strictly related either with machine and/or also project related stuff - I can't recreate issue on my machine

**Comment by qbunia** [comment]
It turned out I had to actually set LongPathsEnabled to 0 to make it work.
